const menu = [
  {
    id: 1,
    title: 'Jajecznica z tostem i bekonem',
    category: 'śniadanie',
    price: 15.99,
    img: 'https://e-przepisykulinarne.pl/wp-content/uploads/2012/04/tost_boczek_jajko-1200x900.jpg',
    desc: `Złocista jajecznica połączona z chrupiącym boczkiem i tostami stanowi smaczne i pożywne danie, które zaspokoi głód na długi czas.`,
  },
  {
    id: 2,
    title: 'Burger z frytkami',
    category: 'obiad',
    price: 13.99,
    img: 'https://www.przyslijprzepis.pl/media/cache/big/uploads/media/recipe/0005/88/7090c2bfb5438fca6c393a263224b7988dcb1be7.jpeg',
    desc: `Kotlet, chrupiące warzywa i ser, a także złociste frytki tworzą połączenie, które zadowoli podniebienia nawet najbardziej wybrednych smakoszy.`,
  },
  {
    id: 3,
    title: 'Risotto z krewetkami i szparagami',
    category: 'kolacja',
    price: 6.99,
    img: 'https://i0.wp.com/blogzapetytem.pl/wp-content/uploads/2019/06/5B8F1E3C-B900-4A20-956B-847DDF0F9F9F.jpeg?fit=2048%2C1552&ssl=1',
    desc: `Risotto z krewetkami i szparagami to danie kuchni włoskiej, które charakteryzuje się kremową konsystencją i wyrazistym smakiem.`,
  },
  {
    id: 4,
    title: 'Szejk czekoladowy',
    category: 'szejki',
    price: 15.99,
    img: 'https://www.bestblender.pl/wp-content/uploads/2014/03/chocolatemilkshakemainjpg.jpg',
    desc: `Szejk czekoladowy z bitą śmietaną i kawałkami ciastek.`,
  },
  {
    id: 5,
    title: 'Amerykańskie naleśniki',
    category: 'śniadanie',
    price: 17.99,
    img: 'https://maslove.pl/wp-content/uploads/2022/06/nalesniki-po-amerykansku-z-syropem-klonowym.jpg',
    desc: `Amerykańskie naleśniki z syropem klonowym i owocami`,
  },
  {
    id: 6,
    title: 'Spaghetti carbonara',
    category: 'obiad',
    price: 18.99,
    img: 'https://www.allrecipes.com/thmb/0USVgLLUxe68kwcVRTe7ZVbWq6M=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/11973-spaghetti-carbonara-II-mfs-044-6fb2128979334fe98c28064e75aa47c9.jpg',
    desc: `Spaghetti Carbonara to klasyczne danie włoskie, które składa się z makaronu spaghetti, jajek, bekonu, sera parmezan i pieprzu.`,
  },
  {
    id: 7,
    title: 'Grillowany stek',
    category: 'kolacja',
    price: 18.99,
    img: 'https://podravkaiovariations.azureedge.net/8d1ede48-640e-11eb-b3f1-0242ac120021/v/f2b1f6a6-64bc-11eb-b6c2-0242ac130010/1024x768-f2b21802-64bc-11eb-a115-0242ac130010.jpeg',
    desc: `Grillowany stek z ziemniakami i warzywami `,
  },
  {
    id: 8,
    title: 'Szejk truskawkowy',
    category: 'szejki',
    price: 12.99,
    img: 'https://static.gotujmy.pl/ZDJECIE_PRZEPISU_ETAP/shake-truskawkowy-358511.jpg',
    desc: `Szejk truskawkowy z lodami waniliowymi i kruszonką`,
  },
  {
    id: 9,
    title: 'Wafle belgijskie',
    category: 'śniadanie',
    price: 13.99,
    img: 'https://f.wszelkieprzepisy.pl/images/4hf9bocr/gofry-belgijskie-orig.png',
    desc: `Wafle belgijskie z owocami i bitą śmietaną`,
  },
  {
    id: 10,
    title: 'Kurczak z ryżem ',
    category: 'obiad',
    price: 24.99,
    img: 'https://static.fajnegotowanie.pl/media/uploads/media_image/auto/recipe-content/1451/mobile/kurczak-tikka-masala.jpg',
    desc: `Kurczak tikka masala z ryżem basmati.`,
  },
  {
    id: 11,
    title: 'Kurczak z ziemniakami',
    category: 'kolacja',
    price: 16.99,
    img: 'https://www.mniammniam.com/obrazki/kurczakpieczonyhcc7.jpg',
    desc: `Kurczak w miodzie i musztardzie z pieczonymi ziemniakami i marchewką`,
  },
  {
    id: 12,
    title: 'Szejk jagodowy',
    category: 'szejki',
    price: 16.99,
    img: './images/menuSzejk1.png',
    desc: `Szejk jagodowy z mlekiem sojowym i musem z jagód.`,
  },
  {
    id: 13,
    title: 'Croissanty z jajkiem',
    category: 'śniadanie',
    price: 8.99,
    img: 'http://2.bp.blogspot.com/-NB6nlS4ew8s/VL1KvgjfjOI/AAAAAAAAD20/nqe7jUCfE1A/s1600/IS_DSC_3016%2Bna%2Bbloga.jpg',
    desc: `Croissanty z jajkiem, szynką i serem to smaczny i pożywny wybór który łączy w sobie chrupiący croissantów z jajkiem, szynką i serem.`,
  },
  {
    id: 14,
    title: 'Filet z ziemniakami',
    category: 'obiad',
    price: 21.99,
    img: 'https://media.centrumrespo.pl/wp-content/uploads/2018/10/18002231/kurczakbok.png',
    desc: `Tagliatelle z krewetkami i szparagami to danie kuchni włoskiej, w którym połączenie krewetek i delikatnych szparagów tworzy niezapomniany smak.`,
  },
  {
    id: 15,
    title: 'Grilowany filet',
    category: 'kolacja',
    price: 13.99,
    img: 'https://static.gotujmy.pl/ZDJECIE_PRZEPISU_ETAP/grillowane-piersi-z-kurczaka-306228.jpg',
    desc: `Grilowany filet z piersi kurczaka z warzywami w piekarniku
    `,
  },
  {
    id: 16,
    title: 'Szejk bananowy',
    category: 'szejki',
    price: 16.99,
    img: 'https://malacukierenka.pl/wp-content/uploads/2011/05/shake-orzechowy-z-bananami.jpg',
    desc: `Szejk bananowy z mlekiem kokosowym i masłem orzechowym`,
  },
];
export default menu;
